<?php

$_conf['ARR_STOP_WORDS'] = array('i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very');

/*
$_conf['ARR_BAD_WORDS'] = array ('arse', 'arsehole', 'asshole', 'bastard', 'bitch', 'blowjob', 'bollocks', 'bondage', 'bugger', 'buggery', 'cock', 'cocked', 'cocksucker', 'crap', 'cum', 'cunt', 'dickhead', 'fuck', 'fucked', 'fucker', 'fucking', 'gayboy', 'motherfucker', 'nigger', 'piss', 'pissed', 'puffter', 'pussy', 'shag', 'shagged', 'shat', 'shit', 'slut', 'twat', 'wank', 'wanker', 'whore');
*/
$_conf['ARR_MONTHS_M'] = array('january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december');

/*
$_conf['ARR_E'] = array('thousand' => 1e3, 'million' => 1e6, 'billion' => 1e9, 'trillion' => 1e12, 'quadrillion' => 1e15, 'quintillion' => 1e18, 'sextillion' => 1e21, 'septillion' => 1e24, 'octillion' => 1e27, 'nonillion' => 1e30, 'decillion' => 1e33, 'undecillion' => 1e36, 'duodecillion' => 1e39, 'tredecillion' => 1e42, 'quattuordecillion' => 1e45, 'quindecillion' => 1e48, 'sexdecillion' => 1e51, 'septendecillion' => 1e54, 'octodecillion' => 1e57, 'novemdecillion' => 1e60, 'vigintillion' => 1e63, 'unvigintillion' => 1e66, 'duovigintillion' => 1e69, 'tresvigintillion' => 1e72, 'quattuorvigintillion' => 1e75, 'quinquavigintillion' => 1e78, 'sesvigintillion' => 1e81, 'septemvigintillion' => 1e84, 'octovigintillion' => 1e87, 'novemvigintillion' => 1e90, 'trigintillion' => 1e93, 'untrigintillion' => 1e96, 'duotrigintillion' => 1e99, 'googol' => 1e100, 'trestrigintillion' => 1e102, 'quattuortrigintillion' => 1e105, 'quinquatrigintillion' => 1e108, 'sestrigintillion' => 1e111, 'septentrigintillion' => 1e114, 'octotrigintillion' => 1e117, 'noventrigintillion' => 1e120, 'quadragintillion' => 1e123, 'quinquagintillion' => 1e153, 'sexagintillion' => 1e183, 'septuagintillion' => 1e213, 'octogintillion' => 1e243, 'nonagintillion' => 1e273);
*/