<?php

/**
* Ajaxel CMS v8.0
* Public translations for "English" language and for "sample" template.
* Generated on 12:57 24-12-2015 from http://alx
* DO NOT EDIT THIS FILE, USE ADMINISTRATION PANEL INSTEAD
*/

$_lang['%1 {number=%1,Comment,Comments}'] = '%1 {number=%1,Comment,Comments}';
$_lang['100% Satisfaction'] = '100% Satisfaction';
$_lang['About Partnering'] = 'About Partnering';
$_lang['About project'] = 'About project';
$_lang['about-partnering-intro'] = 'Partnering is an excellent way to round out skill sets on a per-project basis, and “virtual agencies” are becoming increasingly common. Maybe you want to stay lean and not staff up in every area. Maybe you are transitioning into new territory and need a skilled collaborator. While able to offer a complete package, 
	Ajaxel Studio is also experienced in being a team player.';
$_lang['Advertisement, banner'] = 'Advertisement, banner';
$_lang['Affiliate Program'] = 'Affiliate Program';
$_lang['affiliate-program'] = 'Each month, The Company Corporation helps thousands of businesses incorporate or form Limited Liability Companies. Many of these businesses are referred through our affiliate network. Our affiliates support The Company Corporation by referring entrepreneurs interested in forming a business, and we support our affiliates by providing them commissions, real-time tracking and reporting, and the ability to start their own affiliate networks.';
$_lang['ajaxel-studios'] = 'Ajaxel Web Studio is a family owned and operated company. We pride ourselves on providing value in our products and excellence in our service. We understand what it takes to build websites that not only perform great on Google, but also captivate visitors, help maximize business potential and accelerate profits.';
$_lang['Benefits'] = 'Benefits';
$_lang['benefits-partner'] = '<ul class="tmo_list">
	 <li>Sed malesuada dolor </li>
	<li>Donec non erat metus </li>
	<li>Curabitur ullamcorper nibh </li>
	<li>Pellentesque adipiscing </li>
	<li>Sed nec eros egestas nisl </li>
	<li>Morbi sed nulla ac est cursus </li>
	<li>Vivamus sagittis tristique </li>
	<li>Donec interdum iaculis eros </li>
</ul>';
$_lang['Budget'] = 'Budget';
$_lang['But Who we actually Are'] = 'But Who we actually Are';
$_lang['Characteristic of typical clients, visitors of web-site'] = 'Characteristic of typical clients, visitors of web-site';
$_lang['Company'] = 'Company';
$_lang['Contact'] = 'Contact';
$_lang['Contact us'] = 'Contact us';
$_lang['contact-intro'] = 'Think I might be a good fit for your next web project?<br>
Fill out the form below, give us a call, or drop us a line and tell us about it.';
$_lang['Deadline'] = 'Deadline';
$_lang['Design creation'] = 'Design creation';
$_lang['Design files, documents, technical tasks'] = 'Design files, documents, technical tasks';
$_lang['Domain registration'] = 'Domain registration';
$_lang['Extra works'] = 'Extra works';
$_lang['Facebook or another social'] = 'Facebook or another social';
$_lang['Forums'] = 'Forums';
$_lang['Friend suggests'] = 'Friend suggests';
$_lang['FTP details, MySQL or cPanel username with password'] = 'FTP details, MySQL or cPanel username with password';
$_lang['Google search'] = 'Google search';
$_lang['Hosting'] = 'Hosting';
$_lang['hotscripts.com'] = 'hotscripts.com';
$_lang['How have you found us?'] = 'How have you found us?';
$_lang['how_to_buy_text'] = 'how_to_buy_text';
$_lang['HTML cut from Design'] = 'HTML cut from Design';
$_lang['Information'] = 'Information';
$_lang['I’d Totally Love to Hear from You'] = 'I’d Totally Love to Hear from You';
$_lang['Jessica Fox'] = 'Jessica Fox';
$_lang['Just surfed'] = 'Just surfed';
$_lang['Logout'] = 'Logout';
$_lang['Mailing Address'] = 'Mailing Address';
$_lang['mailing-address'] = 'Nevada street<br/>
South-carolina, Francisco<br/>
Bermuda';
$_lang['Message:'] = 'Message:';
$_lang['More...'] = 'More...';
$_lang['My Profile'] = 'My Profile';
$_lang['Order now'] = 'Order now';
$_lang['Order our services'] = 'Order our services';
$_lang['order-service'] = 'Greetings, I hope you have enjoyed with our works and willing to get something for your own purposes also. Just let me know if so, send detailed information about what you ant and wait for my reply.';
$_lang['Our partners'] = 'Our partners';
$_lang['Partner'] = 'Partner';
$_lang['partner-text'] = 'Whether partnering with design groups, agencies, IT firms, or internal client teams, flexibility, tight process, and solid team communication are key. Hexatrope brings a great wealth of experience in this area, drawn from years of creative collaboration.<br>
<br>
Common scenarios involve things like turn-key web design & build packages, as well as Drupaling your site designs (and consulting on to maximize the opportunities & capabilities this CMS brings). This isn’t a commodity approach where you chuck the design over the wall and hope it comes out, but we work with you in a truly collaborative process of expanding possibilities, shaping experience, and training your end users. Take a look at our breakout on Ajaxel site creation. Any way you slice it, collaboration can provide substantial benefit for all parties when everyone knows how to work together.<br>
<br>
Are you just getting into content managed sites? No problem, we are here to help. Are you looking to go beyond just blogs, and use a well-rounded general CMS (that also does blogs)? Get in touch with us.';
$_lang['Phone or Skype'] = 'Phone or Skype';
$_lang['Programming extra features'] = 'Programming extra features';
$_lang['Project type'] = 'Project type';
$_lang['Quick Contact Form'] = 'Quick Contact Form';
$_lang['Received newsletter'] = 'Received newsletter';
$_lang['Request for a project form'] = 'Request for a project form';
$_lang['Search engine optimization'] = 'Search engine optimization';
$_lang['Send'] = 'Send';
$_lang['seos'] = 'Our team focuses on delivering the industry’s most innovative solutions through stunning corporate grade graphics, W3C standards based source code and white hat SEO strategies. We provide professional web development and SEO management services that can greatly increase your market reach and maximize the performance of your website.';
$_lang['Service List'] = 'Service List';
$_lang['Service Overviews'] = 'Service Overviews';
$_lang['services-intro'] = 'We are a small group of professional web designers and developers who are dedicated to creating powerful, effective and engaging websites.';
$_lang['services-text'] = 'Our bold design style and use of ultra-clean standards-based markup code combine to produce websites that boast exceptional search engine result positions, increased conversions and superior visitor loyalty.<br>
<br>
Ajaxel Web Studio creates strong internet marketing campaigns and effective web presences for small to medium size businesses.<br>
<br>
We specialize in designing powerful branding and developing W3C standards compliant websites that are compatible with the latest devices.';
$_lang['services_list'] = '<ul class="tmo_list">
	<li>PHP and JavaScript Applications</li>
	<li>Custom E-Commerce Solutions</li>
	<li>Effective Marketing Campaigns</li>
	<li>Proven SEO Results</li>
	<li>And many other Developments that are with PHP, JavaScript and domains</li>
</ul>';
$_lang['Similar websites to your project, URL-links'] = 'Similar websites to your project, URL-links';
$_lang['slide1-1'] = 'This is Sample template';
$_lang['slide1-2'] = 'That is just has been installed with Ajaxel CMS';
$_lang['slide1-3'] = 'If any questions, let <a href="http://ajaxel.com/contact">me</a> know';
$_lang['slide2-1'] = 'This is Sample template';
$_lang['slide2-2'] = 'That is just has been installed with Ajaxel CMS';
$_lang['slide2-3'] = 'If any questions, let <a href="http://ajaxel.com/contact">me</a> know';
$_lang['slide3-1'] = 'This is Sample template';
$_lang['slide3-2'] = 'That is just has been installed with Ajaxel CMS';
$_lang['slide3-3'] = 'If any questions, let <a href="http://ajaxel.com/contact">me</a> know';
$_lang['slide4-1'] = 'This is Sample template';
$_lang['slide4-2'] = 'That is just has been installed with Ajaxel CMS';
$_lang['slide4-3'] = 'If any questions, let <a href="http://ajaxel.com/contact">me</a> know';
$_lang['slots_rules'] = 'As a crowdminer you get 1000 free gold nuggets every week to play with.<br>
<br>
You can choose from 1 to 9 lines bet: each line costs 1 nugget so 9 lines will cost 9 nuggets. You can win Gold Coins and the total amount of your winnings will be shown in the scoreboard “Your Weekly Score”.<br>
<br>
When win you can double up, if you decide to double up the game you will see a picture which you will find again behind one of the questions marks. If you win, you will double up your gold coins you just won, if you fail you will lose them all.<br>
<br>
The 10 best players will be included in the “Top 10 List” and they will get the chance to partecipate in the final round to win a 100gr gold bar.
The final round will be on the 14th week, from March 31st to April 6th 2014.<br>
<br>
In the final round all the invited players will get 5000 nuggets and the top player on this round will get a 100gr gold bar.';
$_lang['Testimonial'] = 'Testimonial';
$_lang['Thank you for selecting Ajaxel CMS!'] = 'Thank you for selecting Ajaxel CMS!';
$_lang['w-testimonial'] = 'The best company and I am 100% satisfied =)';
$_lang['We are punctual'] = 'We are punctual';
$_lang['We are reliable'] = 'We are reliable';
$_lang['We use it to upload results directly to hosting.'] = 'We use it to upload results directly to hosting.';
$_lang['we-are'] = 'We are the best company in the world!';
$_lang['we-are-also'] = 'Also we will be even better than the best company in the world!';
$_lang['we-punctual'] = 'We are always outside and inside. You may always catch us with net';
$_lang['we-reliable'] = 'With our company you get everything you need and even more!';
$_lang['we-satis'] = 'We just like working and giving great results for our customers';
$_lang['Why You Should Choose Us'] = 'Why You Should Choose Us';
$_lang['Yesterday in %1'] = 'Yesterday in %1';
$_lang['Your E-mail'] = 'Your E-mail';
$_lang['Your email:'] = 'Your email:';
$_lang['Your website domain'] = 'Your website domain';



